apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nodejs-app-deployment
  labels:
    app: simple-nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-nodejs-app
  template:
    metadata:
      labels:
        app: simple-nodejs-app
    spec:
      containers:
      - name: simple-nodejs-app
        image: triviy/simple-nodejs-app:1.1
        ports:
        - containerPort: 3000
        env:
          - name: REDIS_HOST
            value: redis-clusterip
          - name: REDIS_PORT
            value: '6379'